Run iOS unit tests as part of PR checks

diff --git a/.github/workflows/pr.yml b/.github/workflows/pr.yml
--- a/.github/workflows/pr.yml
+++ b/.github/workflows/pr.yml
@@ -105,9 +105,98 @@ jobs:
           author=$(gh api https://api.github.com/repos/${{ github.repository }}/commits/${head_commit} --jq .author.login)
           echo "commit_author=${author}" >> $GITHUB_OUTPUT
 
+  unit-tests-ios:
+
+      name: Run unit tests (iOS)
+
+      runs-on: macos-13-xlarge
+      timeout-minutes: 30
+
+      outputs:
+        commit_author: ${{ steps.fetch_commit_author.outputs.commit_author }}
+
+      steps:
+
+      - name: Check out the code
+        uses: actions/checkout@v3
+        with:
+          submodules: recursive
+
+      - name: Set cache key hash
+        run: |
+          has_only_tags=$(jq '[ .pins[].state | has("version") ] | all' Package.resolved)
+          if [[ "$has_only_tags" == "true" ]]; then
+            echo "cache_key_hash=${{ hashFiles('Package.resolved') }}" >> $GITHUB_ENV
+          else
+            echo "Package.resolved contains dependencies specified by branch or commit, skipping cache."
+          fi
+
+      - name: Cache SPM
+        if: env.cache_key_hash
+        uses: actions/cache@v3
+        with:
+          path: DerivedData/SourcePackages
+          key: ${{ runner.os }}-spm-ios-${{ env.cache_key_hash }}
+          restore-keys: |
+            ${{ runner.os }}-spm-ios-
+
+      - name: Select Xcode
+        run: sudo xcode-select -s /Applications/Xcode_$(<.xcode-version).app/Contents/Developer
+
+      - name: Run tests
+        run: |
+          set -o pipefail && xcodebuild test \
+            -scheme BrowserServicesKit-Package \
+            -destination 'platform=iOS Simulator,name=iPhone 15' \
+            -derivedDataPath DerivedData \
+            CODE_SIGN_STYLE=Manual \
+            CODE_SIGN_IDENTITY= \
+            CODE_SIGNING_ALLOWED=NO \
+            ENABLE_TESTABILITY=YES \
+            | tee ios-build-log.txt \
+            | xcbeautify --report junit --report-path . --junit-report-filename ios-unittests.xml 
+
+      - name: Publish Unit Tests Report
+        uses: mikepenz/action-junit-report@v3
+        if: always()
+        with:
+          check_name: Test Report
+          report_paths: ios-unittests.xml
+          require_tests: true
+
+      - name: Update Asana with failed unit tests
+        if: always() # always run even if the previous step fails
+        env:
+          ASANA_ACCESS_TOKEN: ${{ secrets.ASANA_ACCESS_TOKEN }}
+          WORKFLOW_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/attempts/${{ github.run_attempt }}
+        run: |
+          # Extract failed tests from the junit report
+          # Only keep failures unique by classname and name (column 1 and 2 of the yq output)
+          yq < tests.xml -p xml -o json -r \
+            $'[.testsuites.testsuite[].testcase] | flatten | map(select(.failure) | .+@classname + " " + .+@name + " \'" + .failure.+@message + "\' ${{ env.WORKFLOW_URL }}") | .[]' \
+            | sort -u -k 1,2 \
+            | xargs -L 1 ./scripts/report-failed-unit-test.sh -s ${{ vars.APPLE_CI_FAILING_TESTS_FAILED_TESTS_SECTION_ID }}
+
+      - name: Upload logs
+        uses: actions/upload-artifact@v3
+        if: always()
+        with:
+          name: ios-build-log.txt
+          path: ios-build-log.txt
+
+      - name: Fetch latest commit author
+        if: always() && github.ref_name == 'main'
+        id: fetch_commit_author
+        env:
+          GH_TOKEN: ${{ github.token }}
+        run: |
+          head_commit=$(git rev-parse HEAD)
+          author=$(gh api https://api.github.com/repos/${{ github.repository }}/commits/${head_commit} --jq .author.login)
+          echo "commit_author=${author}" >> $GITHUB_OUTPUT
+
   create-asana-task:
     name: Create Asana Task
-    needs: [swiftlint, unit-tests]
+    needs: [swiftlint, unit-tests, unit-tests-ios]
 
     if: failure() && github.ref_name == 'main' && github.run_attempt == 1
 
